# Generated by Django 4.1.7 on 2023-11-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watt',
            name='values',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='temperatures',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='watts',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.DeleteModel(
            name='Watt',
        ),
    ]
