# Generated by Django 4.1.7 on 2023-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_watt_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirestoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
